SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
PLAYER_RADIUS = 20
LINE_WIDTH = 2
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3

# Scan mechanic
SCAN_RANGE = 200           # Max distance to scan
SCAN_TIME_QUICK = 1.0      # Quick tag (5 pts)
SCAN_TIME_FULL = 3.0       # Full scan (25 pts)
SCAN_POINTS_QUICK = 5
SCAN_POINTS_FULL = 25
DESTROY_POINTS = 10